#:import utils kivy.utils
<FirstScreen>:
    id:First
    radius: [45, 45, 45, 45]
    name:"First"
    MDBoxLayout:
        size_hint: None, None
        size: root.size
    
        padding:"25dp"
        spacing:"25dp"
        orientation: 'vertical'
        MDSwitch:
            active:not app.theme_cls.theme_style == "Light"
            size_hint:None,None
            width:"40dp"
            pos_hint:{'x':.89,'y':1}
            on_active:app.change_theme(self.active)
        MDLabel:
            id: welcome_label
            text: "WELCOME"
            font_size:"40dp"
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: "15dp"

        MDTextField:
            id: var_num
            text:""
            helper_text: "Enter value from 2 to 4"
            helper_text_mode: "on_error"
            hint_text: "Enter Number Of Variables"
            icon_right: "account"
            size_hint_x: None
            width:"200dp"
            font_size:"18dp"
            pos_hint: {"center_x": 0.5}
            icon_right: "calculator"
            on_text:root.on_text(self.text)

        MDTextField:
            id:const_num
            text:""
            hint_text: "Enter Number Of Constraints"
            helper_text: "Enter Value from 2 to 4"
            helper_text_mode: "on_error"
            icon_right: "calculator"
            size_hint_x: None
            width:"200dp"
            font_size: "18dp"
            pos_hint: {"center_x": 0.5}
            on_text:root.on_text1(self.text)

        MDRoundFlatButton:
            text: "Generate"
            font_size:"20dp"
            size_hint:.5,None
            pos_hint: {"center_x": 0.5}
            on_press: root.changer_next()
            

        MDRoundFlatButton:
            text: "Exit"
            font_size:"20dp"
            size_hint:.5,None
            pos_hint: {"center_x": 0.5} 
            on_press: app.stop()

        Widget:
            size_hint_y: None
            height: "60dp"
<SecondScreen>:
    name:"Second"
<ThirdScreen>:
    name:"Third"
<FourthScreen>:
    name:"Fourth"
    MDBoxLayout:
        id:Box1
        orientation:"vertical"
        MDTopAppBar:
            title:"Simplex Tableau"
            left_action_items:[["arrow-left", lambda x: root.prev()]]

        

    
            
            
